### PR TITLE
Feature/rebranding

### PR DESCRIPTION
**Pull request by asifddlks**
- [x] Replace asil URL(just replace duckduckgo.com with asil.co) in Learn more in web tracking protection
- [x] Replace asil URL (just replace duckduckgo.com with asil.co) in Learn more in global privacy control
- [x] Remove Email protection BETA
- [x] Rebrand Cookie Pop-up Protection  and also repalce asil.co link in the learnmore
- [x] Replace Learn more url in App Tracking protection and also need to replace one image in Who sees your data screen in the Enble process of App Tracking protection 
- [x] Rebrand settings -> about and also replace asil.co link in the help pages
- [x] Fix build issue for deprecated dagger library

### CODE REVIEW

**Comment by denizgencay** [comment]
@asifddlks Hi, did you test the branch if you do I will approve brother, thank you.

**Comment by asifddlks** [comment]
> @asifddlks Hi, did you test the branch if you do I will approve brother, thank you.

I have tested on my side brother. You can test with different build variant brother. That will be great.

**Comment by denizgencay** [comment]
@asifddlks Hi, on development branch di version is 2.48.1 and works fine but this branch throwing build time error. Do you work with PC or Mac?

**Comment by asifddlks** [comment]
> @asifddlks Hi, on development branch di version is 2.48.1 and works fine but this branch throwing build time error. Do you work with PC or Mac?

On MAC brother. Please go ahead if dagger 2.48.1 works work for you. On my side I faced same issue and it killed a huge time to find the culprit (dagger version 🥹).

**Comment by denizgencay** [comment]
@asifddlks Rebranding not working on my Mac I am trying to solve the issues 👍

**Comment by asifddlks** [comment]
> @asifddlks Rebranding not working on my Mac I am trying to solve the issues 👍

@denizgencay Hint: try changing dagger version 2.50 or 2.48.1 whichever works for you.

**Comment by denizgencay** [comment]
@asifddlks As I can see you already changed it back.

**Comment by asifddlks** [comment]
> @asifddlks As I can see you already changed it back.

Is it working now on your Mac?

**Comment by denizgencay** [comment]
@asifddlks Both versions are not working.

**Comment by asifddlks** [comment]
> @asifddlks Both versions are not working.

That's weird. Which JDK version are you using?
Btw, Closed the pull request by accident.

**Comment by denizgencay** [comment]
@asifddlks 17.0.7

**Comment by denizgencay** [comment]
What is yours I can try with your version.

**Comment by asifddlks** [comment]
Mine 17 too.

**Comment by denizgencay** [comment]
@asifddlks That's odd.

**Comment by asifddlks** [comment]
> @asifddlks That's odd.

I had issues with "VpnOnboardingActivity". Whenever I tried to change the "FAQ_WEBSITE" value from DuckDuckGo to Asil url the build issue appeared. I found out that issue is for dagger version. So I changed it.

**Comment by denizgencay** [comment]
@asifddlks Did you pull development to your branch before opening pull request?

**Comment by denizgencay** [comment]
@asifddlks I am facing the same issue, this was happening but when I faced this issue just rebuilding was solving the problem. Now it's not building at all.

**Comment by asifddlks** [comment]
> @asifddlks I am facing the same issue, this was happening but when I faced this issue just rebuilding was solving the problem. Now it's not building at all.

Also I have tried with clean and rebuild. Didn't worked. 
And of course I pulled the development branch before making pull request. You can check rebrand branch has the commit from development.

**Comment by denizgencay** [comment]
@asifddlks Okay brother need to solve this issue, I will let you know when it's done.

**Comment by asifddlks** [comment]
> @asifddlks Okay brother need to solve this issue, I will let you know when it's done.

I will check again tomorrow Insh'Allah. Will sit with you if it needs to resolve building issue on your machine brother.

**Pull request closed without merging**
